### ISSUE TITLE
NVIDIA PRIME

### ISSUE THREAD

**Issue by ventureoo** [ventureoo/nvidia-tweaks#2]
may be soon

**Comment by begin-theadventure** [comment]
Prime tweaks or package?

**Comment by ventureoo** [comment]
> Prime tweaks or package?

No, just a big section about NVIDIA PRIME in the README. Considering that most of the tweaks are already there (enabling default modeset and udev rules for proper operation of dynamic power management). I would like to focus on the PRIME Offload performance issues I encountered when I had a laptop with Intel+NVIDIA.

**Comment by ventureoo** [comment]
Mostly done in https://github.com/ventureoo/nvidia-tweaks/commit/c30f36c13a6df87690a18b4b390d289ef5d18bf7, but there are other things that can be added later.
