### ISSUE TITLE
GDM fix 

### ISSUE THREAD

**Issue by Boria138** [ventureoo/nvidia-tweaks#3]
Можно ли добавить в nvidia-tweaks.conf 
NVreg_PreserveVideoMemoryAllocations = 1 для работы Wayland сессия в GDM  [статья про это на arch wiki](https://wiki.archlinux.org/title/GDM#Wayland_and_the_proprietary_NVIDIA_driver) ? 
И ещё небольшой вопрос почему в секции установка для других дистрибутивов написано скопировать nvidia-tweaks /etc/modprobe.d а в pkgbuild файле для aur он копируется в /usr/lib/modprobe.d ?

**Comment by Boria138** [comment]
Немного поискав я понял что можно отключить проверку NVreg_PreserveVideoMemoryAllocations закоментировав эти две строки 
IMPORT{program}="/bin/sh -c \"sed -e 's/: /=/g' -e 's/\([^[:upper:]]\)\([[:upper:]]\)/\1_\2/g' -e 's/[[:lower:]]/\U&/g' -e 's/^/NVIDIA_/' /proc/driver/nvidia/params\""
ENV{NVIDIA_PRESERVE_VIDEO_MEMORY_ALLOCATIONS}!="1", GOTO="gdm_disable_wayland"
В /usr/lib/udev.d/61-gdm.rules (несмотря на то что на arch wiki написано вообше удалить этот файл)
И ещё нужно включить nvidia-suspend, nvidia-resume, nvidia-hibernate (хотя опять таки на arch wiki написано включить только hibernate и suspens)
Ну и всё это нужно запускать именно в gdm ибо только разработчики гном такие сверх разумы прекрутили функционал гибернации отключения экрана и Wayland на gdm если запускать через что либо другое запуститься только x11

**Comment by ventureoo** [comment]
> Можно ли добавить в nvidia-tweaks.conf NVreg_PreserveVideoMemoryAllocations = 1 для работы Wayland сессия в GDM [статья про это на arch wiki](https://wiki.archlinux.org/title/GDM#Wayland_and_the_proprietary_NVIDIA_driver) ? И ещё небольшой вопрос почему в секции установка для других дистрибутивов написано скопировать nvidia-tweaks /etc/modprobe.d а в pkgbuild файле для aur он копируется в /usr/lib/modprobe.d ?

Путь  `/usr/lib/modprobe.d` выбран намеренно, чтобы пользователь мог переопределять те настройки, которые в нем указаны через файл в `/etc/modprobe.d/`, т.к. modprobe читает в первую очередь файлы из него, иначе говоря файлы в `/etc/modprobe.d` имеют приоритет над теми что в `/usr/lib/modprobe.d`. Если использовать файл в `/etc/modprobe.d/` по умолчанию, то при каждом обновлении пакета/переустановке изменения сделанные в нем пользователем будут перезаписываться, что лично меня не устраивает. Кроме того, сам драйвер пишет дефолтные настройки в `/usr/lib/` и стандартные правила udev от nvidia-utils расположены в `/usr/lib/udev/rules.d/60-nvidia.rules`.

Про отсутствие Wayland сесси в GDM спасибо, я знал об этом, но забыл указать. Хотя лично я предпочитаю просто делать симлинк, т.к. `NVreg_PreserveVideoMemoryAllocations` работает не всегда адекватно и на разных версиях драйвера может вызывать проблемы. Но указать все же стоит.

**Comment by Boria138** [comment]
> > Можно ли добавить в nvidia-tweaks.conf NVreg_PreserveVideoMemoryAllocations = 1 для работы Wayland сессия в GDM [статья про это на arch wiki](https://wiki.archlinux.org/title/GDM#Wayland_and_the_proprietary_NVIDIA_driver) ? И ещё небольшой вопрос почему в секции установка для других дистрибутивов написано скопировать nvidia-tweaks /etc/modprobe.d а в pkgbuild файле для aur он копируется в /usr/lib/modprobe.d ?
> 
> Путь `/usr/lib/modprobe.d` выбран намеренно, чтобы пользователь мог переопределять те настройки, которые в нем указаны через файл в `/etc/modprobe.d/`, т.к. modprobe читает в первую очередь файлы из него, иначе говоря файлы в `/etc/modprobe.d` имеют приоритет над теми что в `/usr/lib/modprobe.d`. Если использовать файл в `/etc/modprobe.d/` по умолчанию, то при каждом обновлении пакета/переустановке изменения сделанные в нем пользователем будут перезаписываться, что лично меня не устраивает. Кроме того, сам драйвер пишет дефолтные настройки в `/usr/lib/` и стандартные правила udev от nvidia-utils расположены в `/usr/lib/udev/rules.d/60-nvidia.rules`.
> 
> Про отсутствие Wayland сесси в GDM спасибо, я знал об этом, но забыл указать. Хотя лично я предпочитаю просто делать симлинк, т.к. `NVreg_PreserveVideoMemoryAllocations` работает не всегда адекватно и на разных версиях драйвера может вызывать проблемы. Но указать все же стоит.

Теперь ясно почему выбран именно этот путь ну а на счёт  NVreg_PreserveVideoMemoryAllocations во втором комментарии я уже указал что он оказывается не обязателен полагаю правильнее будет указать не то что он плохо работает а то что его проверку можно отключить ну и про службы тоже нужно сказать они почему-то не включены по умолчанию

**Comment by Boria138** [comment]
А и ещё поскольку у меня нет аккаунта на Codeberg, а в ARU на гите нет ошибок, напишу сюда. В ARU написано, что можно отказаться от DM и запускаться через startx, но в Gnome так лучше не делать, особенно если у тебя ноутбук, ибо гибернация, режим ожидания и выключение экрана привязано к GDD. И ещё Wayland сессия на Nvidia (а может вообше везде, тут не проверял) работать не будет. Даже если прописать в startx запуск именно Wayland или, например, использовать более лёгкий Lightdm, то запускаться будут только иксы.

**Comment by Boria138** [comment]
Пишу спустя три недели потому что оказалась что всё можно починить просто изменив строчку ```ENV{NVIDIA_PRESERVE_VIDEO_MEMORY_ALLOCATIONS}!="1" ``` на ```ENV{NVIDIA_PRESERVE_VIDEO_MEMORY_ALLOCATIONS}!="0" ``` где нибудь в /etc/udev/rules.d и тогда Wayland сессия будет работать пользователь легко сможет это если что удалить и все это не слетит при обновлении GDM в общем на этом можно считать проблему закрытой а добавлять это изменение в новую версию nvidia-tweaks или нет это уже вам решать потому что делать симлинк в /dev/null это как по мне не очень хорошая идея так как на старых видеокартах эти правила нужны а вот убрать одно по сути не нужное правило мне кажется будет правильнее
