### ISSUE TITLE
Add options fbdev=1 after latest nvidia drivers release 545

### ISSUE THREAD

**Issue by ChaoticChrono** [ventureoo/nvidia-tweaks#6]

**Comment by ventureoo** [comment]
I wasn't able to test this on my laptop as my framebuffer management is handled by the iGPU. So I'm waiting for some feedback from desktop GPUs users. For some people, this fixes Wayland-related issues:
https://forums.developer.nvidia.com/t/kde-wayland-doesnt-work-on-the-545-drivers/269794/3

**Comment by vlad196** [comment]
I installed nvidia-framebuffer for myself and have been using it for about a month. 
I didn't see any problems or improvements. Maybe the display manager appears more smoothly. 
I don't know much about framebuffer and I need to be shown what to look at, but so far I don't see any problems.
Here is my logs with framebuffer:
[logs-grep_fb.log](https://github.com/ventureoo/nvidia-tweaks/files/13537477/logs-grep_fb.log)
If necessary, I can check some tests from you

**Comment by vlad196** [comment]
> I installed nvidia-framebuffer for myself and have been using it for about a month. I didn't see any problems or improvements. Maybe the display manager appears more smoothly. I don't know much about framebuffer and I need to be shown what to look at, but so far I don't see any problems. Here is my logs with framebuffer: [logs-grep_fb.log](https://github.com/ventureoo/nvidia-tweaks/files/13537477/logs-grep_fb.log) If necessary, I can check some tests from you

After 3 days, I noticed that I couldn't get out of sleep mode without problems
https://forums.developer.nvidia.com/t/545-29-02-fbdev-1-cause-nvidia-drm-flip-event-timeout-on-boot-errors/272829

**Comment by ventureoo** [comment]
I added a patch that fixes the boot errors "nvidia-drm Flip event timeout":  https://github.com/ventureoo/nvidia-tweaks/commit/ebf73f43fb58c44115ce21dc11590ed3c54c3e16

https://forums.developer.nvidia.com/t/545-29-06-18-1-flip-event-timeout-error-on-startup-shutdown-and-sometimes-suspend-wayland-unusable/274788/20

**Comment by ventureoo** [comment]
NVIDIA 550 beta is out and I think most of the issues have been fixed?

**Comment by ryanmusante** [comment]
Not the explicit sync fixes yet unfortunately

**Comment by ventureoo** [comment]
> Not the explicit sync fixes yet unfortunately

I was talking about issues with fbdev, but yes, explicit sync was not added as well as support for Wayland tearing protocol.

**Comment by ventureoo** [comment]
The `fbdev=1` looks mostly stable right now, so done.
