### ISSUE TITLE
AUR package opinion, shouldn't have been removed so quickly

### ISSUE THREAD

**Issue by SheMelody** [ventureoo/nvidia-tweaks#8]
I'm on upstream Arch Linux, tried both regular NVIDIA drivers, open, beta and open beta and modeset still sets to 0 by default for me. I think you should have kept the package for a slightly longer timespan until these upstream changes actually merged into available repos?

`sudo cat /sys/module/nvidia_drm/parameters/modeset` outputs `N` after removing `nvidia-tweaks`, running `sudo mkinitcpio -P` and rebooting.

`sudo cat /sys/module/nvidia_drm/parameters/modeset` outputs `Y` after manually setting `modeset=1`

This applies to all the drivers I tried above.

**Comment by ventureoo** [comment]
Hi. Can you please specify which `nvidia-utils` packages you are using? I'm also pretty sure that nvidia-utils already had, at the time AUR package was removed, a patch to enable modeset by default: https://gitlab.archlinux.org/archlinux/packaging/packages/nvidia-utils/-/blob/main/make-modeset-fbdev-default.patch Not sure about nvidia-utils-beta.

**Comment by SheMelody** [comment]
> Hi. Can you please specify which `nvidia-utils` packages you are using? I'm also pretty sure that nvidia-utils already had, at the time AUR package was removed, a patch to enable modeset by default: https://gitlab.archlinux.org/archlinux/packaging/packages/nvidia-utils/-/blob/main/make-modeset-fbdev-default.patch Not sure about nvidia-utils-beta.

At the time of creating this issue, my Arch Linux was fully updated, so I was running the latest version indeed. I still had to specify `modeset=1`.

If you want, I can retry, I'm again fully updated. I won't be trying soon enough because I'm doing a few things that will take a while.

Edit: I clearly see the patch there, this is weird, I'll dive deeper into this then.

**Comment by SheMelody** [comment]
Closing this. This was because of a dependency mess pacman made when switching back and forth through versions, so I fixed them myself.
